# Generated by Django 5.2 on 2025-04-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("angle0", models.IntegerField()),
                ("angle0_min", models.IntegerField()),
                ("angle0_max", models.IntegerField()),
                ("len0", models.IntegerField()),
                ("angle1", models.IntegerField()),
                ("angle1_min", models.IntegerField()),
                ("angle1_max", models.IntegerField()),
                ("len1", models.IntegerField()),
                ("angle2", models.IntegerField()),
                ("angle2_min", models.IntegerField()),
                ("angle2_max", models.IntegerField()),
                ("len2", models.IntegerField()),
                ("angle3", models.IntegerField()),
                ("angle3_min", models.IntegerField()),
                ("angle3_max", models.IntegerField()),
                ("len3", models.IntegerField()),
                ("angle4", models.IntegerField()),
                ("angle4_min", models.IntegerField()),
                ("angle4_max", models.IntegerField()),
                ("len4", models.IntegerField()),
                ("angle5", models.IntegerField()),
                ("angle5_min", models.IntegerField()),
                ("angle5_max", models.IntegerField()),
                ("len5", models.IntegerField()),
            ],
        ),
    ]
