# Generated by Django 5.2 on 2025-04-16 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0002_robot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="angle0",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(-180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="angle1",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(-180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="angle2",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(-180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="angle3",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(-180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="angle4",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(-180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="angle5",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(-180),
                ]
            ),
        ),
    ]
