# Generated by Django 5.2 on 2025-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0006_robot_a0_robot_a1_robot_a2_robot_a3_robot_a4_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="a0",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="a1",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="a2",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="a3",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="a4",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="a5",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="len0",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="len1",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="len2",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="len3",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="len4",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="len5",
            field=models.IntegerField(),
        ),
    ]
